volumes:
  postgres_data:
    driver: "local"
  maven_cache:

networks:
  wise_network:
    driver: "bridge"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_conexao_saude
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ:-America/Sao_Paulo}
      - WHATSAPP_SERVICE_TOKEN:${WHATSAPP_SERVICE_TOKEN}
      - GEMINI_SERVICE_TOKEN:${GEMINI_SERVICE_TOKEN}
    ports:
        - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - wise_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
